modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/tchojnacki/LogicCircuitBoards/issues"
showAsResourcePack=false

license="MIT"

[[mods]]
modId="mcpcb"
version="1.0.3"
displayName="Logic Circuit Boards"
logoFile="logo.png"
authors="tchojnacki"
description="Compress your redstone logic gates to a single block printed circuit boards."

[[dependencies.mcpcb]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.mcpcb]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
